import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen flex justify-center items-center m-0">
        <div className="w-full max-w-5xl h-full flex flex-col justify-center bg-slate-500">
          {children}
        </div>
      </body>
    </html>
  );
}
